server {
    listen 80;

    # Serve os arquivos do Vue
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redireciona chamadas /api para o Backend Java
    location /api/ {
        proxy_pass http://lojinha-app:8080/; # O nome deve ser igual ao do docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}